FROM encuestas_app

RUN mkdir -p /usr/src/app

COPY . /usr/src/app

WORKDIR /usr/src/app

RUN npm install && \
    npm install async && \
    npm install -g mocha

CMD ["mocha", "test", "--reporter", "spec"]