version: '2'

services:
  db:
    image: mongo
  app:
    mem_limit: 1024m
    cpu_quota: 50000
    cpuset: '0'
    memswap_limit: 0
    mem_reservation: 0
    mem_swappiness: 0
    build: ./
    environment:
      DOCKER_MONGODB_URI: "mongodb://db/test"
    depends_on:
      - db
    ports:
      - "3000:3000"