version: '2'

services:
  haproxy:
    image: eeacms/haproxy
    depends_on:
    - app
    ports:
    - "3000:5000"
    - "1936:1936"
    environment:
      BACKENDS_PORT: 3000
      BACKENDS: "app"
      DNS_ENABLED: "true"
  db:
    image: mongo
  app:
    mem_limit: 2000m
    cpu_quota: 100000
    cpuset: '0'
    mem_swappiness: 0
    build: ./
    environment:
      DOCKER_MONGODB_URI: "mongodb://db/test"
    depends_on:
      - db