version: '2'

services:
  app:
    build: ./
    environment:
      MONGO_URL: "mongodb://database/test"
    links:
      - database # link this service to the database service
    ports:
      - "3000:3000"
  database: # name of the third service
    image: mongo # specify image to build container from
    ports:
      - "27017:27017" # specify port forewarding